### ISSUE TITLE
CSS for Decoration

### ISSUE THREAD

**Issue by oslego** [WebPlatformLondon/speakers#1]
CSS has powerful features intended for decoration: linear and radial gradients, backgrounds, shadows, filters, blend-modes, and many others. Their apparent complexity and ever-changing "design trends" means they're often underused and overlooked, sometimes replaced with unnecessary piles of HTML and black magic CSS with side effects so fragile that nobody dares touch ever again.

This talk is a collection of examples and practical use cases for CSS decoration features: generated polygon backgrounds, skeleton interfaces as replacements for loading indicators, gradient borders, tool UI details, like range input backgrounds, rulers and grid lines.

Everything done using standards-compliant CSS. No black magic, I promise.
## Bio

Razvan is a web developer at Adobe where he builds tools and technology to make life easier for web designers and developers.

https://twitter.com/razvancaliman 

Photo: https://dl.dropboxusercontent.com/u/362306/Razvan_CALIMAN.jpg

**Comment by ghost** [comment]
This talk is scheduled for the 7th of June.

@gnclmorais @matteofigus Do you have thoughts, or questions for @oslego ?

**Comment by ghost** [comment]
Talk added to the 7th June event: http://www.meetup.com/WebPlatform-London/events/231095694/

**Comment by gnclmorais** [comment]
Nothing at all, everything looks great! I just saw your talk on [JSConf UE](https://www.youtube.com/watch?v=zvG97aOfAJM&hd=1) and it was 👌

**Comment by oslego** [comment]
Thank you! Glad you liked it.

One question: how much time do I have for the talk at this meetup? The
content in its current form requires at least 30min, but I can go a bit
longer as well.

**Comment by matteofigus** [comment]
Hi @oslego,

I think the plan is to do something like
- My intro 2 mins
- First talk 30 mins-ish (by @philpl)
- a couple of 5 mins lighting talks if there are any
- Second talk (yours) 30-40 mins ish

In this case, being last, you should have the chance to go on a little bit longer if you need. Does it work for you?

**Comment by oslego** [comment]
Hi, Matteo!

Yes, that works for me. Thanks!

**Comment by matteofigus** [comment]
Thanks! I loved your talk

**Comment by oslego** [comment]
Thank you for the opportunity to speak! 
Glad you enjoyed it.
