### ISSUE TITLE
Observe the Future with Observables

### ISSUE THREAD

**Issue by kitten** [WebPlatformLondon/speakers#2]
Observables are the new kid on the block, being standardised for ECMAScript 7, and bring yet another concept from Functional Programming to JavaScript. As a mix between a _stream of events_ and an _iterable over time_, Observables allow you to handle all kinds of asynchronous behaviour by writing short and intuitive code. As your front end apps become increasingly complex, this can be your way out.

This talk introduces the basic concept observables and its practical use cases. Furthermore it will teach you some basic RxJS, the most commonly used Observable library. And to get your feet wet, it will present some real life examples.
## Bio

Phil is a front end developer at Pie Mapping building a line-haul management platform. In his free time he codes React, RxJS and general JavaScript libraries and projects.

https://twitter.com/_philpl

**Comment by kitten** [comment]
@matteofigus This might be too vague (Bio too) ;) I'm pretty bad at pushing out longer texts quickly

**Comment by matteofigus** [comment]
Lol, no worries, I think it is very good and very interesting.

Would you be free for June 7th?

**Comment by kitten** [comment]
@matteofigus that should work

**Comment by ghost** [comment]
@philpl I love this topic! ES7!! Functional programming!!111!!!

**Comment by matteofigus** [comment]
This is great, so @franciov can we add this on meetup.com?

**Comment by ghost** [comment]
Talk officially scheduled: http://www.meetup.com/WebPlatform-London/events/231095694/

**Comment by matteofigus** [comment]
Thanks Phil, it was very very good!
