### ISSUE TITLE
Progressive Web Applications

### ISSUE THREAD

**Issue by tpgmartin** [WebPlatformLondon/speakers#3]
## Abstract

Progressive web applications promise to enable users to experience a more native app experience, with greater speed and reliability across a range of browsers and network reliability. Four key components come together to produce a progressive web application: service workers, cache API, indexedDB, and manifest file. Though there are experimental features, we can make use of lots of these technologies today with the latest stable browser releases.

This talk covers the basics of the technologies used to realise progressive web apps, with a few demonstrations and code samples from a live app. 
## Bio

Tom is a full stack web developer at OpenTable

[https://twitter.com/tpgmartin](https://twitter.com/tpgmartin)

**Comment by matteofigus** [comment]
I really like this, service workers are very very interesting. I think we are ok for the next one (June 7th) but maybe we can start thinking about a date for the July one @gnclmorais ? Not sure @franciov will be here in July 😢

**Comment by ghost** [comment]
@tpgmartin This is a great topic, thanks for submitting! @matteofigus Yea, I don't think I'll be able to attend the event in July, but happy to help online! Is live streaming / recording feasible? :)

**Comment by gnclmorais** [comment]
@tpgmartin, that sounds great! 🙇  Thank you!

@matteofigus, looking at my calendar, July 5-6 look like promising days. 💔  that @franciov won’t be around, though. 😭

**Comment by matteofigus** [comment]
Scheduled for Dec 14th https://www.meetup.com/WebPlatform-London/events/236089771/
